class CreatePersonas < ActiveRecord::Migration
  def self.up
    create_table :personas do |t|
      t.string :nombres
      t.string :a_paterno
      t.string :a_materno
      t.string :empresa
      t.string :cargo
      t.string :tel_oficina
      t.string :tel_particular
      t.string :tel_movil
      t.string :tel_fax
      t.string :direc_calle
      t.string :direc_colonia
      t.string :direc_cp
      t.string :direc_int
      t.string :direc_ext
      t.string :direc_delegacion
      t.string :email
      t.string :pag_web
      t.string :notas
      t.string :tel_oficina_ext
      t.string :dia_cumple
      t.string :mes_cumple
      t.string :anio_cumple
      t.date :fecha_nacimiento
      t.string :asistente
      t.string :nacionalidad

      t.timestamps
    end

    Persona.create(:nombres => "Arturo Abimael 00", :a_paterno => "Quijada", :a_materno => "Mendoza", 
      :empresa => "root technologies", :cargo => "Desarrollador", :tel_oficina => "123", :tel_particular => "456",
      :tel_movil => "789", :tel_fax => "000", :direc_calle => "Monterrey",
      :direc_colonia => "Roma", :direc_cp => "06700", :direc_int => "18", :direc_ext => "122", :email => "aabimael@gmail.com",
      :pag_web => "totis.tv", :notas => ";-)", :fecha_nacimiento => "2009-03-31 18:22:12.5", :asistente => "NO tiene :-(")

    Persona.create(:nombres => " ", :a_paterno => " ", :email => "hportobelo@hotmail.com", :tel_oficina => "3614 6714 /3614 6751 ", :tel_movil => " ", :empresa => "Hotel Portobelo ", :cargo => "")
    Persona.create(:nombres => " ", :a_paterno => " ", :email => "contacto@redlemon.com.mx", :tel_oficina => "1084 0378 ", :tel_movil => "55 5104 6965 ", :empresa => "Red Lemon ", :cargo => "")
    Persona.create(:nombres => " ", :a_paterno => " ", :email => "", :tel_oficina => "5534 9044 / 5524 2345 ", :tel_movil => " ", :empresa => "Taxi ", :cargo => "")
    Persona.create(:nombres => " ", :a_paterno => " ", :email => "", :tel_oficina => "5543 6419/ 9151 5446 ", :tel_movil => "55 3196 3091 ", :empresa => "Cerrajería  Star ", :cargo => "")
    Persona.create(:nombres => "ABRIL ", :a_paterno => "MARTÍNEZ GÓMEZ ", :email => "abril_martinez@malo.com.mx", :tel_oficina => "55 98 39 63/56 15 81 79 ", :tel_movil => " ", :empresa => "Martínez López y Asociados  S.C ", :cargo => "ABOGADO")
    Persona.create(:nombres => "Adriana ", :a_paterno => "Sánchez ", :email => "", :tel_oficina => "5622 48 99 ", :tel_movil => " ", :empresa => "UNAM ", :cargo => "Personal")
    Persona.create(:nombres => "Alberto ", :a_paterno => "Segura Yáñez ", :email => "ventas@seguraimprenta.com", :tel_oficina => "5588 9910 / 5588 9057 ", :tel_movil => " ", :empresa => "Segura ", :cargo => "")
    Persona.create(:nombres => "Alberto Lenin ", :a_paterno => "Zabre Zuloaga ", :email => "", :tel_oficina => "55 98 39 63/52 58 94 55 ", :tel_movil => "04455 5412 3981 ", :empresa => "Martínez López y Asociados  S.C ", :cargo => "Abogado")
    Persona.create(:nombres => "ALDRIN ", :a_paterno => "CARRILLO ", :email => "aldrin.carrillo@telmex.com", :tel_oficina => "01 800 232 77 66 ", :tel_movil => " ", :empresa => "TELMEX ", :cargo => "ASESOR TELMEX (INGENIERO)")
    Persona.create(:nombres => "Alejandra ", :a_paterno => "Olvera ", :email => "alejandra@tek-mart.com", :tel_oficina => "(222)403 4759 (Puebla) ", :tel_movil => " ", :empresa => "Tekmart ", :cargo => "")
    Persona.create(:nombres => "Alejandro ", :a_paterno => "González Muñoz ", :email => "alexgonzalezm@casenet.com.mx", :tel_oficina => "1054 4864 ", :tel_movil => " ", :empresa => "case ", :cargo => "Director General")
    Persona.create(:nombres => "Alejandro ", :a_paterno => "Hernández ", :email => "alejhernandez@deloittemx.com", :tel_oficina => "50 80 63 76 ", :tel_movil => " ", :empresa => "Deloitte ", :cargo => "Gerente Impuestos")
    Persona.create(:nombres => "Alejandro ", :a_paterno => "Lira Luna ", :email => "alejandro.lira@ca.com", :tel_oficina => "53 87 54 57 ", :tel_movil => "55 38 99 06 57 ", :empresa => "ca ", :cargo => "Account Director")
    Persona.create(:nombres => "Alejandro ", :a_paterno => "López ", :email => "alopez@siga.com.mx", :tel_oficina => "5661 0535 ext. 801 ", :tel_movil => " ", :empresa => "SIGA Integrador de Soluciones ", :cargo => "Coordinador")
    Persona.create(:nombres => "Alfonsina ", :a_paterno => "Ávila Romay ", :email => "avilaa@redmedicasur.org.mx", :tel_oficina => "5666 9232 / 5528 8253 ", :tel_movil => "5230 3030 clave 10312 ", :empresa => "Derma Integral ", :cargo => "")
    Persona.create(:nombres => "Ángel ", :a_paterno => "Islava ", :email => "", :tel_oficina => " ", :tel_movil => "5523 33 5856 ", :empresa => "Cámara de Senadores ", :cargo => "Secretario Particular")
    Persona.create(:nombres => "ANGÉLICA ", :a_paterno => "SOTO ARELLANOS ", :email => "angelica.soto@jackbe.com", :tel_oficina => "5553 41 20– 5553 07 68 ", :tel_movil => "Ext. 33 ", :empresa => "JACKBE ", :cargo => "CUENTAS POR COBRAR")
    Persona.create(:nombres => "Antonio ", :a_paterno => "Cruz ", :email => "", :tel_oficina => "53872400 x 18155 / 18199 ", :tel_movil => " ", :empresa => "INM ", :cargo => "Director de Sistemas y Telecom")
    Persona.create(:nombres => "Antonio ", :a_paterno => "Miranda Cortés ", :email => "amirandac@bansefi.gob.mx", :tel_oficina => "5481 3485 ", :tel_movil => " ", :empresa => "Bansefi ", :cargo => "Director de Administración y Control Integral")
    Persona.create(:nombres => "ANTONIO ", :a_paterno => "RAMÍREZ ", :email => "tonio@nucleares.unam.mx", :tel_oficina => "56 22 46 76 ", :tel_movil => " ", :empresa => "INSTITUTO DE CIENCIAS NUCLEARES ", :cargo => "UNIDAD DE CÓMPUTO")
    Persona.create(:nombres => "Antonio ", :a_paterno => "Rubio ", :email => "antonio.rubio@wissenmx.com", :tel_oficina => " ", :tel_movil => " ", :empresa => "Wissen ", :cargo => "")
    Persona.create(:nombres => "Antonio ", :a_paterno => "Sandoval Leyva ", :email => "antonio.sandoval@datavision.com.mx", :tel_oficina => "5273 2903 ext. 28 ", :tel_movil => "55 1948 4995 ", :empresa => "DATA VISION ", :cargo => "Gerente General")
    Persona.create(:nombres => "Antonio ", :a_paterno => "Zazueta N ", :email => "antonioz@amarillonetworks.com", :tel_oficina => "5575 0022 ", :tel_movil => "1019 9258 ", :empresa => "Amarillo networks ", :cargo => "Gerente de Operaciones")
    Persona.create(:nombres => "ARACELI ", :a_paterno => "GONZÁLEZ ", :email => "araceli@tek-mart.com", :tel_oficina => "01 (222)  403 47 58 ", :tel_movil => "11 63 83 91 (DF) ", :empresa => "TEKMART ", :cargo => "")
    Persona.create(:nombres => "Armando ", :a_paterno => "Álvarez ", :email => "aralvarez@fibraoptica.com", :tel_oficina => "56 89 58 52 ", :tel_movil => " ", :empresa => "ESPECIALISTAS EN FIBRA OPTICA , S.A. DE C.V. ", :cargo => "")
    Persona.create(:nombres => "Armida ", :a_paterno => "Aldecoa Andraca ", :email => "", :tel_oficina => "25815614 ", :tel_movil => "044 55 18 85 96 15 ", :empresa => "Procesar ", :cargo => "")
    Persona.create(:nombres => "ARTURO ", :a_paterno => "ARROYO DE ANDA RUIZ ", :email => "", :tel_oficina => "91 49 13 71 ", :tel_movil => " ", :empresa => "IMPRESOR DE FACTURAS ", :cargo => "")
    Persona.create(:nombres => "Arturo ", :a_paterno => "Rajlevsky S. ", :email => "arturo@4microsaft.com", :tel_oficina => "52671918 ", :tel_movil => "04455 29558340 ", :empresa => "Microsoft ", :cargo => "Solution Sales Specialist")
    Persona.create(:nombres => "ARTURO ", :a_paterno => "SÁNCHEZ ", :email => "asanchez@humancm.com.mx", :tel_oficina => "90 00 39 04 ", :tel_movil => "35 40 31 36 NEXTEL ", :empresa => "GRUPO HCM ", :cargo => "")
    Persona.create(:nombres => "ARTURO ", :a_paterno => "VÁZQUEZ CORONA ", :email => "vaz@root.com.mx", :tel_oficina => "56 87 27 70 ", :tel_movil => "04455 5406 83 14 ", :empresa => "ROOT TECHNOLOGIES ", :cargo => "DIRECTOR DE TECNOLOGÍAS")
    Persona.create(:nombres => "ARTURO ABIMAEL ", :a_paterno => "QUIJADA MENDOZA ", :email => "abimael@root.com.mx", :tel_oficina => "56 87 27 70 ", :tel_movil => "044 55 29 01 81 80 ", :empresa => "ROOT TECHNOLOGIES ", :cargo => "PROGRAMADOR")
    Persona.create(:nombres => "Austin ", :a_paterno => "Wenzel ", :email => "a.wenzel@tideway.com", :tel_oficina => "+1 866 863 1776 ", :tel_movil => " ", :empresa => "Tideway ", :cargo => "")
    Persona.create(:nombres => "BANCO ", :a_paterno => "BANAMEX ", :email => "www.banamex.com", :tel_oficina => "12 26 26 39 ", :tel_movil => " ", :empresa => "BANAMEX ", :cargo => "")
    Persona.create(:nombres => "BANCO ", :a_paterno => "INBURSA ", :email => "", :tel_oficina => "5202 02 23 ", :tel_movil => " ", :empresa => "INBURSA ", :cargo => "")
    Persona.create(:nombres => "BOLSA DE TRABAJO ", :a_paterno => " ", :email => "", :tel_oficina => " ", :tel_movil => " ", :empresa => "UVM ", :cargo => "")
    Persona.create(:nombres => "Bryron Renato ", :a_paterno => "Durán Menéndez ", :email => "direccion@migracion.gob.gt", :tel_oficina => "(502)24112405 ext. 8013 ", :tel_movil => " ", :empresa => "Gobierno de Guatemala ", :cargo => "Interventor")
    Persona.create(:nombres => "C.P Rigoberto ", :a_paterno => "Aldama ", :email => "", :tel_oficina => "5387 24 00 x 18309 ", :tel_movil => " ", :empresa => "INM ", :cargo => "Subdirección de Recursos Materiales")
    Persona.create(:nombres => "Cándido ", :a_paterno => "Vigil Fragoso ", :email => "cvigilf@mmm.com", :tel_oficina => "5270 2186 ", :tel_movil => "55 5452 7863 ", :empresa => "3M ", :cargo => "Gerente de Ventas y MKTG")
    Persona.create(:nombres => "CANEK ", :a_paterno => "VÁZQUEZ ", :email => "canek_vazquez@hotmail.com", :tel_oficina => "5345 32 41 ", :tel_movil => " ", :empresa => "CAMARA DE SENADORES ", :cargo => "")
    Persona.create(:nombres => "CARLOS ", :a_paterno => "BELTRÁN MENDOZA ", :email => "carlos@powercolor.com.mx", :tel_oficina => "24 75 20 87 ", :tel_movil => "55 66 76 81 52*15º36958 ", :empresa => "POWER COLOR S.A. DE C.V. ", :cargo => "")
    Persona.create(:nombres => "Carlos ", :a_paterno => "Bermúdez ", :email => "carlos.bermudez.vargas@oracle.com", :tel_oficina => "(506) 205 5523 ", :tel_movil => " ", :empresa => "ORACLE ", :cargo => "Channel Manager")
    Persona.create(:nombres => "Carlos ", :a_paterno => "Castro ", :email => "ccastro@mail.dgsa.unam.mx", :tel_oficina => "5622 9694 ", :tel_movil => " ", :empresa => "DGSA UNAM ", :cargo => "")
    Persona.create(:nombres => "CARLOS ", :a_paterno => "GARCÍA ", :email => "", :tel_oficina => "52 79 58 00 ", :tel_movil => " ", :empresa => "MULTIVA ", :cargo => "")
    Persona.create(:nombres => "Carlos ", :a_paterno => "Mena ", :email => "cmena@mx1.ibm.com", :tel_oficina => "52703722 ", :tel_movil => "5518877646 ", :empresa => "Cortázar ", :cargo => "Business Development")
    Persona.create(:nombres => "CAROLINA ", :a_paterno => "QUIROZ ", :email => "", :tel_oficina => "55 98 03 91 ", :tel_movil => " ", :empresa => "XIOMARA ", :cargo => "")
    Persona.create(:nombres => "CENTEL ", :a_paterno => "CENTEL ", :email => "", :tel_oficina => "5278 99 01  EXT456 ", :tel_movil => " ", :empresa => "CENTEL ", :cargo => "")
    Persona.create(:nombres => "César ", :a_paterno => "Pérez Herrejon ", :email => "cepe@sisorg.com.mx", :tel_oficina => "5256 45 17 ", :tel_movil => "55 5407 76 47 ", :empresa => "SIS KLE ", :cargo => "  BI Business Unit Manager")
    Persona.create(:nombres => "César ", :a_paterno => "Reyes López ", :email => "crl@cfe.gob.mx", :tel_oficina => "54817514 / 5229 4400 ", :tel_movil => " ", :empresa => "CFE ", :cargo => "Subgerente de Estudios de Riesgo")
    Persona.create(:nombres => "CITLALI ", :a_paterno => "CALDERON DE ANDA ", :email => "citlali@root.com.mx", :tel_oficina => "56 87 27 70 ", :tel_movil => "04455 27 11 52 64 ", :empresa => "ROOT TECHNOLOGIES ", :cargo => "LIDER DE PROYECTOS")
    Persona.create(:nombres => "Charles ", :a_paterno => "Rattray ", :email => "c.rattray@tideway.com", :tel_oficina => "001 917 608 4619 ", :tel_movil => " ", :empresa => "Tideway ", :cargo => "Sales")
    Persona.create(:nombres => "Daniel ", :a_paterno => "Ramírez Morales ", :email => "diradmon@litografica-delta.com.mx", :tel_oficina => "5590 53 99 x 182 ", :tel_movil => " ", :empresa => "Litográfica Delta ", :cargo => "Director de Administración")
    Persona.create(:nombres => "DAVID ", :a_paterno => "CORONA LOPEZ ", :email => "davichoco@gmail.com", :tel_oficina => " ", :tel_movil => "04455 15 01 28 11 ", :empresa => " ", :cargo => "LÍDER DE PROYECTO")
    Persona.create(:nombres => "DAVID ", :a_paterno => "GODÍNEZ DE LA ROSA ", :email => "printer_com@hotmail.com", :tel_oficina => "55 16 15 19 ", :tel_movil => " ", :empresa => "PRINTER.COM ", :cargo => "Impresor")
    Persona.create(:nombres => "David ", :a_paterno => "Nieto Hernandez ", :email => "david.nieto@wissenmx.com", :tel_oficina => "(442) 2347076 ", :tel_movil => "5554330774 ", :empresa => "WISSEN Tecnología y Educación ", :cargo => "Director General")
    Persona.create(:nombres => "DAVID ", :a_paterno => "RIVERA RODRIGUEZ ", :email => "david.rivera.rodriguez@banorte.com", :tel_oficina => "55 23 55 56/55 23 79 48 ", :tel_movil => " ", :empresa => "BANORTE ", :cargo => "PROMOTOR JR.")
    Persona.create(:nombres => "DAYSOFT ", :a_paterno => " ", :email => "", :tel_oficina => "55 24 74 58/55 24 30 74 ", :tel_movil => " ", :empresa => "DAYSOFT ", :cargo => "")
    Persona.create(:nombres => "Delia Ruby ", :a_paterno => "Álvarez Moreno ", :email => "deliarubyalvarezmoreno@yahoo.com", :tel_oficina => "(502) 23 31 86 86 ", :tel_movil => " ", :empresa => "Regas y Asociados ", :cargo => "Secretaria")
    Persona.create(:nombres => "EDGAR ", :a_paterno => "MORALES ", :email => "edgar_morales@pronomina.com.mx", :tel_oficina => "36 26 29 29 ", :tel_movil => "044 55 54 12 12 98 ", :empresa => "SERVICIOS PROF. DE NÓMINA Y R.H. ", :cargo => "DIRECTOR GENERAL")
    Persona.create(:nombres => "Edgard ", :a_paterno => "Valdez ", :email => "edgard.valdez@axtel.com.mx", :tel_oficina => "50921825 ", :tel_movil => "36233694 ", :empresa => "Axtel ", :cargo => "Gerente Diseño de Soluciones de Gobierno")
    Persona.create(:nombres => "Edilberto ", :a_paterno => "Gil Bravo ", :email => "egil@reduno.com.mx / egil@telmex.com", :tel_oficina => "5624 4281 / 56244200 ", :tel_movil => " ", :empresa => "Red Uno ", :cargo => "Gerente de Cuenta")
    Persona.create(:nombres => "EDUARDO ", :a_paterno => "BOYOLI MUÑOZ ", :email => "eduardo.boyoli@gmail.com", :tel_oficina => "5202 09 61/1989 88 18 ", :tel_movil => " ", :empresa => "DERECHO CORPORATIVO Y PROPIEDAD INDUSTRIAL ", :cargo => "")
    Persona.create(:nombres => "Eduardo ", :a_paterno => "Cervantes ", :email => "cervantes_eduardo@hotmail.com", :tel_oficina => "53453898 ", :tel_movil => "5543530910 ", :empresa => "Senado de la República ", :cargo => "Encargado Web")
    Persona.create(:nombres => "Efraín ", :a_paterno => "Sánchez ", :email => "efrain.sanchez@oracle.com", :tel_oficina => "9178 3064 ", :tel_movil => "55 1333 5075 ", :empresa => "ORACLE ", :cargo => "Senior Technologist")
    Persona.create(:nombres => "ELISA MARIA ", :a_paterno => "GARCIA FLORES ", :email => "elisamaria_12@hotmail.com", :tel_oficina => "00 502 23 66 81 72 ", :tel_movil => "00502 5587 16 40 ", :empresa => "CONTADORES DE GUATEMALA ", :cargo => "CONTADORA")
    Persona.create(:nombres => "Elvia ", :a_paterno => "Martínez Viveros ", :email => "emartinez@centrogeo.org.mx", :tel_oficina => "26152508  ext. 120 ", :tel_movil => " ", :empresa => "CONACYT ", :cargo => "Asesora de la Dirección General")
    Persona.create(:nombres => "Empleo Federal ", :a_paterno => " ", :email => "", :tel_oficina => " ", :tel_movil => " ", :empresa => " ", :cargo => "")
    Persona.create(:nombres => "ENRIQUE ", :a_paterno => "GALINDO NAVA ", :email => "egalindo@fumec.org", :tel_oficina => "52 00 05 60 EXT 1288-202 ", :tel_movil => " ", :empresa => "FUNDACION MEXICO-ESTADOS UNIDOS PARA LA CIENCIA ", :cargo => "SISTEMA DE ASISTENCIA TECNOLÓGICO EMPRESARIAL")
    Persona.create(:nombres => "Enrique ", :a_paterno => "Martínez ", :email => "", :tel_oficina => "3871 3828 ", :tel_movil => "04455 36-35-90-69 ", :empresa => "Todo Impreso ", :cargo => "Impresor")
    Persona.create(:nombres => "Enrique ", :a_paterno => "Martínez  Arrieta ", :email => "enrique.martinez@guycarp.com", :tel_oficina => "9140 7054 ", :tel_movil => "55 5407 8706 ", :empresa => "Guy Carpenter ", :cargo => "Vice  Presidente Latin America")
    Persona.create(:nombres => "ENRIQUE ", :a_paterno => "PALACIOS BONETA ", :email => "enrique.palacios@nucleares.unam.mx", :tel_oficina => "56224680 ", :tel_movil => " ", :empresa => "INSTITUTO DE CIENCIAS NUCLEARES ", :cargo => "UNIDAD DE CÓMPUTO")
    Persona.create(:nombres => "Erick ", :a_paterno => "Ayala ", :email => "Eayala@mx.imshealth.com", :tel_oficina => "50625221 ", :tel_movil => " ", :empresa => "ims ", :cargo => "Sr. Mgr. Production LA Mexico")
    Persona.create(:nombres => "Erick ", :a_paterno => "Morales ", :email => "", :tel_oficina => "53872400 x 18219 ", :tel_movil => " ", :empresa => "INM ", :cargo => "")
    Persona.create(:nombres => "Erika ", :a_paterno => "Miranda Ordoñez ", :email => "emiranda@marsystems.com.mx", :tel_oficina => "5601 26 99/5601 35 20 ", :tel_movil => " ", :empresa => "MAR Systems, S,A de C.V. ", :cargo => "")
    Persona.create(:nombres => "Erika ", :a_paterno => "Rendón Rahal ", :email => "erika.rendon@ingrammicro.com.mx", :tel_oficina => "5263 65 00 x 1904 ", :tel_movil => "55 5402 8209 ", :empresa => "Ingram Mexico ", :cargo => "Ejecutivo")
    Persona.create(:nombres => "Erika ", :a_paterno => "Villalobos ", :email => "erika@daisyplanet.com.mx", :tel_oficina => "4196 0555 ", :tel_movil => " ", :empresa => "Daisy Planet ", :cargo => "")
    Persona.create(:nombres => "Eugenio Othon ", :a_paterno => "Chilhuaqueño ", :email => "eugenio@root.com.mx", :tel_oficina => "53 45 38 05 ", :tel_movil => "04455 14 51 97 35 ", :empresa => "Root Technologies S.C. ", :cargo => "Analista")
    Persona.create(:nombres => "Everardo ", :a_paterno => "Rodríguez Caro ", :email => "ecaror@amib.com.mx", :tel_oficina => "57266987 ext. 6987 ", :tel_movil => " ", :empresa => "AMIB ", :cargo => "Subdirector Técnico de Operaciones")
    Persona.create(:nombres => "Fabiola ", :a_paterno => "Anaya Doll ", :email => "fabiola@daisyplanet.com.mx", :tel_oficina => "41 96 05 00 ", :tel_movil => "10419602 ", :empresa => "DAISY PLANET ", :cargo => "")
    Persona.create(:nombres => "FACULTAD DE CIENCIAS NUCLEARES ", :a_paterno => " ", :email => "", :tel_oficina => "56 22 48 11 ", :tel_movil => " ", :empresa => " ", :cargo => "CONTABILIDAD")
    Persona.create(:nombres => "Fausto ", :a_paterno => "Chávez ", :email => "", :tel_oficina => "2581 5732 ", :tel_movil => " ", :empresa => "Procesar ", :cargo => "")
    Persona.create(:nombres => "Fernanda ", :a_paterno => "Ojeda Delgado ", :email => "fernanda.ojeda@ingrammicro.com.mx", :tel_oficina => "5263 65 68 ", :tel_movil => "55 2270 6734 ", :empresa => "INGRAM Mexico ", :cargo => "CISCO Sales Specialist")
    Persona.create(:nombres => "FERNANDO ", :a_paterno => "GUTIERREZ ", :email => "fernando@tek-mart.com", :tel_oficina => "55 (222) 40 34 758 ", :tel_movil => "04455 54 04 44 64 ", :empresa => "TEKMART ", :cargo => "")
    Persona.create(:nombres => "Fernando J. ", :a_paterno => "Irure López ", :email => "firure@mx1.ibm.com", :tel_oficina => "5270-6071 ", :tel_movil => "55 2095 7451 ", :empresa => "IBM ", :cargo => "Sales specialist")
    Persona.create(:nombres => "FLOR ", :a_paterno => "MORENO ", :email => "", :tel_oficina => "55 57 39 40 ", :tel_movil => " ", :empresa => "OPERADORA DI, S.C. ", :cargo => "ENCARGADA")
    Persona.create(:nombres => "FLOR ", :a_paterno => "TRUJILLO ", :email => "", :tel_oficina => "25 81 57 27 ", :tel_movil => " ", :empresa => "PROCESAR ", :cargo => "")
    Persona.create(:nombres => "FLOR IVETTE ", :a_paterno => "MÉNDEZ OROZCO ", :email => "flormdz@dukhroma.com", :tel_oficina => "56 96 78 53 ", :tel_movil => "04455 13 63 57 16 ", :empresa => "DUKHROMA ", :cargo => "GERENTE DE MARKETING")
    Persona.create(:nombres => "Francisco ", :a_paterno => "López González ", :email => "lopez@malo.com.mx", :tel_oficina => "55 98 39 63 / 56 15 81 79 ", :tel_movil => " ", :empresa => "Martínez López y Asociados S.C. ", :cargo => "Abogado")
    Persona.create(:nombres => "FRANCISCO ", :a_paterno => "SOLSONA CRUZ ", :email => "solsona@acm.org", :tel_oficina => "56 22 48 04 ", :tel_movil => " ", :empresa => "FACULTAD DE CIENCIAS ", :cargo => "COORDINADOR DE LOS SERVICIOS DE CÓMPUTO")
    Persona.create(:nombres => "Fred A. ", :a_paterno => "Schellenberg ", :email => "schellenbergfa@state.gov", :tel_oficina => "50802961 ", :tel_movil => " ", :empresa => "Embajada USA ", :cargo => "Coordinador de  Programas")
    Persona.create(:nombres => "GABRIELA ", :a_paterno => "GARCÍA ", :email => "ggarcia@marsystems.com.mx", :tel_oficina => " ", :tel_movil => " ", :empresa => "MAR SYSTEMS ", :cargo => "GERENTE DE ADMINISTRACIÓN")
    Persona.create(:nombres => "Gabriela ", :a_paterno => "Hernández ", :email => "", :tel_oficina => "58453067 y 58453097 ", :tel_movil => " ", :empresa => "Industrias Menvar ", :cargo => "")
    Persona.create(:nombres => "Gadi ", :a_paterno => "Mokotov P. ", :email => "gadi@guibor.com.mx", :tel_oficina => "5514 2093 / 5525 0564 ", :tel_movil => "5331 8811 ", :empresa => "guibor ", :cargo => "Director General")
    Persona.create(:nombres => "Gerardo ", :a_paterno => "León Rodríguez ", :email => "jglrodriguez@allnativesystems.com", :tel_oficina => "55334942 ", :tel_movil => "55 2178 7337 ", :empresa => "Allnative Systems ", :cargo => "Especialista en Sistemas")
    Persona.create(:nombres => "Gerardo ", :a_paterno => "Pescador Gutiérrez ", :email => "gerardo.pescador@vvda.com.mx", :tel_oficina => "36 26 07 31 ", :tel_movil => "04455 14 74 76 82 ", :empresa => "VVDA Soluciones, S.A. De C.V. ", :cargo => "")
    Persona.create(:nombres => "Gerardo ", :a_paterno => "Quiroz ", :email => "", :tel_oficina => "51302200 ext. 1580 ", :tel_movil => " ", :empresa => "Senado ", :cargo => "Abogado")
    Persona.create(:nombres => "Gerardo ", :a_paterno => "Tapia ", :email => "", :tel_oficina => "844 438 0722 ", :tel_movil => " ", :empresa => "Gobierno de Coahuila ", :cargo => "")
    Persona.create(:nombres => "Global Taxis ", :a_paterno => " ", :email => "", :tel_oficina => "5803 2888 y   5648 2888 ", :tel_movil => " ", :empresa => "Global Taxis ", :cargo => "")
    Persona.create(:nombres => "Gloria Gabriela ", :a_paterno => "Moncayo Cisneros ", :email => "gmoncayo@consar.gob.mx", :tel_oficina => "3000 2656 ", :tel_movil => " ", :empresa => "CONSAR ", :cargo => "Directora de Planeación Industrial")
    Persona.create(:nombres => "Gustavo ", :a_paterno => "De la Fuente ", :email => "gustavo.delafuente@axtel.com.mx", :tel_oficina => "50921570 ", :tel_movil => "24742781 ", :empresa => "Axtel ", :cargo => "Gerente Soluciones ITC")
    Persona.create(:nombres => "Gustavo ", :a_paterno => "Santiago López ", :email => "gsantiag@reduno.com.mx", :tel_oficina => "54907219 /54907200 X 7219 ", :tel_movil => " ", :empresa => "Reduno ", :cargo => "Gerente Comercial")
    Persona.create(:nombres => "Gustavo A. ", :a_paterno => "Erosa Figueroa ", :email => "gaerosa@ssp.df.gob.mx", :tel_oficina => "52425039 ext. 5263, 6155 ", :tel_movil => " ", :empresa => "Secretaría de Seguridad Pública ", :cargo => "Director de Informática")
    Persona.create(:nombres => "GYT CONTINENTAL ", :a_paterno => " ", :email => "", :tel_oficina => "00 (502) 23 38 68 01 ", :tel_movil => " ", :empresa => " ", :cargo => "ASISTENCIA")
    Persona.create(:nombres => "HARIM ", :a_paterno => "GONZÁLEZ ", :email => "wtc@maxicopias.com", :tel_oficina => "90 00 30 31 /90 00 30 32 ", :tel_movil => "04455 29 80 24 15 ", :empresa => "MAXICOPIAS ", :cargo => "GERENTE DE SUCURSAL")
    Persona.create(:nombres => "HECTOR ", :a_paterno => "GARRIDO BORRAYO ", :email => "hector.garrido@jackbe.com", :tel_oficina => "52 86 79 26/52 86 24 52 ", :tel_movil => "EXT. 27 ", :empresa => "JACKBE ", :cargo => "VENTAS")
    Persona.create(:nombres => "HECTOR ", :a_paterno => "PEREZ GALINDO ", :email => "", :tel_oficina => "25 81 58 20 ", :tel_movil => "04455 18 67 63 73 ", :empresa => "PROCESAR ", :cargo => "")
    Persona.create(:nombres => "HECTOR ", :a_paterno => "PEREZ ROBLES ", :email => "", :tel_oficina => "57 21 64 14 ", :tel_movil => "04455 54 31 04 55 ", :empresa => " ", :cargo => "")
    Persona.create(:nombres => "Héctor ", :a_paterno => "Barbone ", :email => "hectorb@arscite.com", :tel_oficina => " ", :tel_movil => "55 3660 6375 ", :empresa => "ARS Cite ", :cargo => "")
    Persona.create(:nombres => "Héctor ", :a_paterno => "Navarro Hernández ", :email => "hhernandez@allnativesystems.com", :tel_oficina => "29745452 ", :tel_movil => "04455-1478-9556 ", :empresa => "ALL NATIVE SYSTEMS, L.L.C ", :cargo => "Contador General")
    Persona.create(:nombres => "HECTOR JESUS ", :a_paterno => "MUÑOZ GUTIÉRREZ ", :email => "jesus@root.com.mx", :tel_oficina => "56 87  27 70 ", :tel_movil => "044 55 17 54 04 48 ", :empresa => "ROOT TECHNOLOGIES ", :cargo => "DISEÑADOR")
    Persona.create(:nombres => "HERIBERTO ", :a_paterno => "RUIZ TAFOYA ", :email => "hrtafoya@fumec.org", :tel_oficina => "5200 05 60 EXT 128 ", :tel_movil => " ", :empresa => "FUNDACIÓN MÉXICO-ESTADOS UNIDOS PARA LA CIENCIA ", :cargo => "ASESOR TECNOLÓGICO EMPRESARIAL DEL SATE")
    Persona.create(:nombres => "Ina ", :a_paterno => "Becerril ", :email => "ibecerri@mx1.ibm.com", :tel_oficina => "52703955 ", :tel_movil => "5538995134 ", :empresa => "IBM ", :cargo => "Ejecutiva de Cuenta")
    Persona.create(:nombres => "INBURSA ", :a_paterno => " ", :email => "", :tel_oficina => "52 02 02 23 ", :tel_movil => " ", :empresa => "BANCO INBURSA ", :cargo => "")
    Persona.create(:nombres => "Ing. Antonio Arturo ", :a_paterno => "Cruz Zamora ", :email => "acruz@inami.gob.mx", :tel_oficina => "53872437 ", :tel_movil => " ", :empresa => "SEGOB ", :cargo => "")
    Persona.create(:nombres => "Ing. J. Enrique ", :a_paterno => "González  Villaseñor ", :email => "señorvilla@hotmail.com", :tel_oficina => "55884970 ", :tel_movil => " ", :empresa => " ", :cargo => "Dir. General de Ingeniería de Tránsito")
    Persona.create(:nombres => "Ingrid ", :a_paterno => "Pérez Barrientos ", :email => "", :tel_oficina => "502 23 62 83 67 al 70 ", :tel_movil => "502 5688 29 22 ", :empresa => "OIM ", :cargo => "")
    Persona.create(:nombres => "INSTITUTO CULTURAL MEXICANO JAPONES, A.C. ", :a_paterno => " ", :email => "", :tel_oficina => "55 44 29 89 ", :tel_movil => " ", :empresa => "ESCUELA ", :cargo => "")
    Persona.create(:nombres => "ISAAC ", :a_paterno => "OSORIO FERNANDEZ ", :email => "", :tel_oficina => "56 69 06 89/5669 09 42 ", :tel_movil => " ", :empresa => "ISLARK EUGENIA ", :cargo => "OFICINAS")
    Persona.create(:nombres => "ISABEL ", :a_paterno => "GONZALEZ ", :email => "", :tel_oficina => "5709 50 00/ 3418 ", :tel_movil => " ", :empresa => "FARMACIAS PARIS ", :cargo => "")
    Persona.create(:nombres => "ITAM BOLSA DE TRABAJO ", :a_paterno => " ", :email => "bolsa@itam.mx", :tel_oficina => "56 28 40 00 ", :tel_movil => " ", :empresa => "ITAM ", :cargo => "")
    Persona.create(:nombres => "IVAN ", :a_paterno => "CARREÓN VÁZQUEZ ", :email => "ivan@root.com.mx", :tel_oficina => "56 87 27 70 ", :tel_movil => "04455 32 72 58 64 ", :empresa => "ROOT TECHNOLOGIES ", :cargo => "PROGRAMADOR")
    Persona.create(:nombres => "IVAR GENARO ", :a_paterno => "HERNÁNDEZ GONZÁLEZ ", :email => "ivar@root.com.mx", :tel_oficina => "56 87 27 70 ", :tel_movil => "55 38 88 87 91/5515107582 ", :empresa => "ROOT TECHNOLOGIES ", :cargo => "ASISTENTE ADMINISTRATIVO")
    Persona.create(:nombres => "IXE ", :a_paterno => "DIRECTO ", :email => "", :tel_oficina => "5174 20 00 ", :tel_movil => " ", :empresa => "IXE ", :cargo => "")
    Persona.create(:nombres => "IXE ", :a_paterno => "NET ", :email => "", :tel_oficina => "5004 13 92 ", :tel_movil => " ", :empresa => " ", :cargo => "")
    Persona.create(:nombres => "JACOB ", :a_paterno => "LOBACO ", :email => "jacob@root.com.mx", :tel_oficina => "56 87 27 70 ", :tel_movil => "5515114147 ", :empresa => "ROOT TECHNOLOGIES ", :cargo => "PROGRAMADOR")
    Persona.create(:nombres => "JAIME ", :a_paterno => "VAZQUEZ ", :email => "jaime.vazquez@evmuebles.com.mx", :tel_oficina => "52 76 41 03 ", :tel_movil => "2735 8825 ", :empresa => "EV Muebles y Equipos de Oficinas, S. A. de C. V. ", :cargo => "")
    Persona.create(:nombres => "Jaime ", :a_paterno => "Villaseñor Zertuche ", :email => "jaimev@indeval.com.mx", :tel_oficina => "5726 6855 ", :tel_movil => " ", :empresa => "SD INDEVAL ", :cargo => "Chief Risk Officer and Development Manager")
    Persona.create(:nombres => "Jaime A. ", :a_paterno => "Rendón ", :email => "jrendon@mx.imshealth.com", :tel_oficina => "50 62 52 06 ", :tel_movil => "5539937657 ", :empresa => "IMS Health ", :cargo => "Information Management Manager")
    Persona.create(:nombres => "Jaime Ulises ", :a_paterno => "Guerrero Hidalgo ", :email => "julisesgro@yahoo.coom.mx", :tel_oficina => "5682 2286 ", :tel_movil => "55 3927  5940 ", :empresa => "Consultoría Laboral ", :cargo => "Licenciado en derecho")
    Persona.create(:nombres => "Jesús Rubén ", :a_paterno => "Caudillo Herrera ", :email => "rcaudillo@inami.gob.mx", :tel_oficina => "5387 2546 ", :tel_movil => " ", :empresa => "INAMI ", :cargo => "Coordinador de Planeación e Investigación")
    Persona.create(:nombres => "JONATHAN ", :a_paterno => "ZERTUCHE OÑATE ", :email => "jonathan.zertuche@gcisgroup.com.mx", :tel_oficina => "91 50 44 36 ", :tel_movil => "1990 36 41 ", :empresa => "GCIS ", :cargo => "")
    Persona.create(:nombres => "Jorge ", :a_paterno => "Escamilla ", :email => "", :tel_oficina => " ", :tel_movil => " 55 1452 17 88 ", :empresa => " ", :cargo => "Mensajero")
    Persona.create(:nombres => "JORGE ", :a_paterno => "GUERRA ", :email => "jorgeg@hisoft.com.mx", :tel_oficina => "59 79 20 20 ", :tel_movil => " ", :empresa => "HI SOFT S.A. DE C.V. ", :cargo => "DIRECTOR GENERAL")
    Persona.create(:nombres => "Jorge ", :a_paterno => "Hernández ", :email => "jorhern@cisco.com", :tel_oficina => "5267 1165 ", :tel_movil => "55 2270 0905 ", :empresa => "Cisco Systems de México S.A de C.V ", :cargo => "Systems Engineer")
    Persona.create(:nombres => "Jorge ", :a_paterno => "Olmos ", :email => "jolmos@microsoft.com", :tel_oficina => "1253 6764 ", :tel_movil => "55 4186 8276 ", :empresa => "fast ", :cargo => "Sales Director Mexico")
    Persona.create(:nombres => "Jorge E. ", :a_paterno => "Medina ", :email => "jorge.medina@i2inc.com", :tel_oficina => "+1 (703) 9210195 ", :tel_movil => "+1 (703) 6084099 ", :empresa => "i2 Grupo ", :cargo => "Director General para America Latina")
    Persona.create(:nombres => "Jorge Luis ", :a_paterno => "Espinosa Trujano ", :email => "jespinoza@itera.com.mx", :tel_oficina => "55 33 00 06 50 ", :tel_movil => "04455 5413 8091 ", :empresa => "itera ", :cargo => "Consultor Jurídico")
    Persona.create(:nombres => "Jorge Luis ", :a_paterno => "Ibarra ", :email => "jorge.ibarra@sat.gob.mx", :tel_oficina => "9157 2581/58021951 e 1078 ", :tel_movil => "55 2690 1005 ", :empresa => "SAT ", :cargo => "Administrador General de Comunicaciones y TI")
    Persona.create(:nombres => "José ", :a_paterno => "Cruz Dávila ", :email => "jose.davila@axtel.com.mx", :tel_oficina => "01 81 8997 11 79 ", :tel_movil => " ", :empresa => "AXTEL ", :cargo => "")
    Persona.create(:nombres => "José ", :a_paterno => "Morales ", :email => "jose.morales@i2inc.com", :tel_oficina => "703 8424762 ", :tel_movil => "571 225 9382 ", :empresa => "i2 Grupo ", :cargo => "Technical Consultant")
    Persona.create(:nombres => "José Antonio ", :a_paterno => "Cifuentes ", :email => "joseantonio.cifuentes@axtel.com.mx", :tel_oficina => "50921736 ", :tel_movil => "13254607 ", :empresa => "Axtel ", :cargo => "Dir. Servicios Integrados")
    Persona.create(:nombres => "José Antonio ", :a_paterno => "Jiménez ", :email => "antonio.jimenez@wissenmx.com", :tel_oficina => " ", :tel_movil => "5532226179 ", :empresa => "WISSEN S.C. ", :cargo => "")
    Persona.create(:nombres => "JOSÉ CARLOS ", :a_paterno => "MEDRANO MIGUEL ", :email => "altimpresa@hotmail.com", :tel_oficina => "56 48 79 09 ", :tel_movil => "04455 21 79 44 26 ", :empresa => "ALTERNATIVA IMPRESA, S.A. DE C.V. ", :cargo => "EJECUTIVO DE VENTAS")
    Persona.create(:nombres => "JOSE LUIS ", :a_paterno => "REYES ", :email => "", :tel_oficina => "52 79 58 00 ", :tel_movil => "ext 4569 ", :empresa => "MULTIVA ", :cargo => "")
    Persona.create(:nombres => "JUAN ", :a_paterno => "FRANJOSA ", :email => "", :tel_oficina => "26 14 51 80 ", :tel_movil => "04455 14 46 04 43 ", :empresa => " ", :cargo => "")
    Persona.create(:nombres => "JUAN ", :a_paterno => "JUÁREZ ", :email => "juan.juarez@gcis.com.mx", :tel_oficina => "91 50 44 36 ", :tel_movil => "1990 3642 ", :empresa => "GCIS ", :cargo => "")
    Persona.create(:nombres => "Juan ", :a_paterno => "Uribe ", :email => "", :tel_oficina => "5622 4809 ", :tel_movil => " ", :empresa => "UNAM ", :cargo => "Jefe Personal")
    Persona.create(:nombres => "JUAN ANTONIO ", :a_paterno => "BARCENAS ", :email => "abarcenas@gmail.com", :tel_oficina => "56 04 28 01 / 56 04 21 27 ", :tel_movil => " ", :empresa => "HUNKABANN ", :cargo => "")
    Persona.create(:nombres => "Juan Carlos ", :a_paterno => "Ursua Illescas ", :email => "jursua@migracion.gob.gt", :tel_oficina => "00 502 2411 2412 ", :tel_movil => " ", :empresa => "OIM ", :cargo => "Director Adjunto DGM")
    Persona.create(:nombres => "Juan Daniel ", :a_paterno => "Canchola ", :email => "jcanchol@mx1.ibm.com", :tel_oficina => "5270 3941 ", :tel_movil => "55 5270 6712 ", :empresa => "IBM ", :cargo => "Information Management Manager México and Centro A")
    Persona.create(:nombres => "JUAN DE DIOS ", :a_paterno => "ROSAS DÍAZ ", :email => "juan@root.com.mx", :tel_oficina => "5687 27 70 ", :tel_movil => "04455 16 48 39 20 ", :empresa => "ROOT TECHNOLOGIES ", :cargo => "PROGRAMADOR")
    Persona.create(:nombres => "Juan Martín ", :a_paterno => "Segovia Aldape ", :email => "jsegovia@fifomi.gob.mx", :tel_oficina => "52 49 95 00 ext. 4520 ", :tel_movil => " ", :empresa => "FIFOMI ", :cargo => "Subgerente de Administración de Riesgos")
    Persona.create(:nombres => "Juan Pablo ", :a_paterno => "Sánchez Uriarte ", :email => "jpsanchez@ixe.com.mx", :tel_oficina => "50 04 10 65 / 5268 9000 ", :tel_movil => " ", :empresa => "IXE ", :cargo => "Subdirector Ixe Directo")
    Persona.create(:nombres => "Julio César ", :a_paterno => "Nieves Pavón ", :email => "julion@microsoft.com", :tel_oficina => "5267 2043 ", :tel_movil => "55 1451 5836 ", :empresa => "Microsoft ", :cargo => "Engagament Manager")
    Persona.create(:nombres => "Kelly K. ", :a_paterno => "Albert ", :email => "kalbert@allnativeservices.com", :tel_oficina => "55334942 ", :tel_movil => " ", :empresa => "All Native Systems L.L.C ", :cargo => "Operations Site Manager")
    Persona.create(:nombres => "LAURA ", :a_paterno => "PULIDO ", :email => "amberes68@yahoo.com.mx", :tel_oficina => "91 49 37 58/55 25 62 15 ", :tel_movil => " ", :empresa => "IMPRESOS AMBERES ", :cargo => "")
    Persona.create(:nombres => "Laura ", :a_paterno => "Roldán ", :email => "", :tel_oficina => "53453000 Ext. 3412 ", :tel_movil => "55 1891 2164 ", :empresa => "Becentenario ", :cargo => "Encargada")
    Persona.create(:nombres => "Lauro ", :a_paterno => "Sánchez ", :email => "", :tel_oficina => "04455 2883 9944 ", :tel_movil => " ", :empresa => " ", :cargo => "Carpintero")
    Persona.create(:nombres => "Lenin ", :a_paterno => "Zabre ", :email => "lenin.zabre@zabreybujaidar.com", :tel_oficina => "5543 61 77 ", :tel_movil => " ", :empresa => "Zabre y Bujaidar S.C. ", :cargo => "Abogado")
    Persona.create(:nombres => "Leticia ", :a_paterno => "Hernández Torres ", :email => "lhernand@procesar.com", :tel_oficina => "2581 5852 ", :tel_movil => " ", :empresa => "PROCESAR ", :cargo => "Gerente Jurídico y Corporativo")
    Persona.create(:nombres => "LETICIA ", :a_paterno => "JÍMENEZ ", :email => "", :tel_oficina => "56 22 26 79 ", :tel_movil => " ", :empresa => "UNAM ", :cargo => "PROVEEDURIA")
    Persona.create(:nombres => "LIC. CARLOS ALBERTO ", :a_paterno => "GARCÍA REGÁS ", :email => "cagregas@yahoo.com", :tel_oficina => "(502) 23 31 86 86 ", :tel_movil => "(502) 52 06 25 19 ", :empresa => "ABOGADO (GUATEMALA) ", :cargo => "ABOGADO")
    Persona.create(:nombres => "Lic. Ismerai ", :a_paterno => " ", :email => "", :tel_oficina => "5387 24 00 x 18395 ", :tel_movil => " ", :empresa => "INM ", :cargo => "Responsable de Contratos")
    Persona.create(:nombres => "LIC. LOURDES ", :a_paterno => "TORIS ", :email => "itorices@mx.up.mx", :tel_oficina => "54 82 16 00/ 54 82 17 00 ", :tel_movil => " ", :empresa => "UP ", :cargo => "")
    Persona.create(:nombres => "LIC. MARIA FERNANDA ", :a_paterno => "GUTIERREZ SANCHEZ ", :email => "mgutierrez@procesar.com", :tel_oficina => "25 81 57 04 ", :tel_movil => " ", :empresa => "PROCESAR ", :cargo => "JURÍDICO")
    Persona.create(:nombres => "Lic. Natividad ", :a_paterno => "Juárez ", :email => "", :tel_oficina => "5130 22 00 x 6206 ", :tel_movil => " ", :empresa => "Cámara de Senadores ", :cargo => "")
    Persona.create(:nombres => "LILIANA ", :a_paterno => "GONZÁLEZ MORALES ", :email => "liliana@root.com.mx", :tel_oficina => "56 87 27 70 ", :tel_movil => "04455 38 88 99 83 ", :empresa => "ROOT TECHNOLOGIES ", :cargo => "DIRECTORA DE ADMINISTRACIÓN")
    Persona.create(:nombres => "Liliana ", :a_paterno => "Vidal ", :email => "liliana@daisyplanet.com.mx", :tel_oficina => "41 96 05 00 ", :tel_movil => "10 19 71 69 ", :empresa => "Daisy Planet ", :cargo => "Administración")
    Persona.create(:nombres => "Lorena ", :a_paterno => "Ibáñez Rojas ", :email => "libañez@iusacell.com.mx", :tel_oficina => "85825293 ", :tel_movil => "04455 10235106 ", :empresa => "Grupo IUSACELL ", :cargo => "Gerente de Desarrollo Tecnológico")
    Persona.create(:nombres => "Lorenzo ", :a_paterno => "Ramírez Mateos ", :email => "lramirez@infonavit.org.mx", :tel_oficina => "5322 6879 ", :tel_movil => "55 1353 1253 ", :empresa => "INFONAVIT ", :cargo => "Gerente de administración e Infraestructura")
    Persona.create(:nombres => "Los Olivos ", :a_paterno => " ", :email => "", :tel_oficina => "56 69 01 16 ", :tel_movil => " ", :empresa => " ", :cargo => "")
    Persona.create(:nombres => "Lourdes ", :a_paterno => "Gómez Nava ", :email => "lourdes.gomez@promexico.gob.mx", :tel_oficina => "5447 7000 / 5449 9000 ", :tel_movil => " ", :empresa => "PROMÉXICO ", :cargo => "Unidad de Inteligencia de Negocios")
    Persona.create(:nombres => "Luciano ", :a_paterno => "Díaz ", :email => "luciano.diaz@nucleares.unam.mx", :tel_oficina => "56 22 47 39 EXT 250 ", :tel_movil => " ", :empresa => "Instituto de Ciencias Nucleares ", :cargo => "")
    Persona.create(:nombres => "Luis ", :a_paterno => "Isselin Lira ", :email => "isselin@cisco.com", :tel_oficina => "5267 1644 ", :tel_movil => "55 2699 9913 ", :empresa => "Cisco Systems, Inc. ", :cargo => "SE-Public Sector")
    Persona.create(:nombres => "Luis Alberto ", :a_paterno => "Monge Fuentes ", :email => "luis.monge.fuentes@oracle.com", :tel_oficina => "(506) 2055556 y 2055500 ", :tel_movil => "(506) 8575556 ", :empresa => "ORACLE ", :cargo => "ISV Manager")
    Persona.create(:nombres => "Luis Alejandro ", :a_paterno => "Díaz Barreiro Ascencio ", :email => "luis@root.com.mx", :tel_oficina => " ", :tel_movil => "4190 25 77 ", :empresa => "Root Technologies S.C. ", :cargo => "")
    Persona.create(:nombres => "Luis Antonio ", :a_paterno => "Aguilar Guerrero ", :email => "luisaguilargro@gmail.com", :tel_oficina => "045 667 131 14 07 ", :tel_movil => "04455 32 53 77 90 ", :empresa => " ", :cargo => "")
    Persona.create(:nombres => "LUIS GUILLERMO ", :a_paterno => "GONZÁLEZ OBREGÓN ", :email => "guillermo@root.com.mx", :tel_oficina => "56 87 27 70 ", :tel_movil => "04455 18 34 17 63 ", :empresa => "ROOT TECHNOLOGIES ", :cargo => "PROGRAMADOR")
    Persona.create(:nombres => "Luis Manuel ", :a_paterno => "Martínez Ruiz ", :email => "lmmartinezr@inami.gob.mx", :tel_oficina => "5387 2400 x 18172 ", :tel_movil => "5541 77 77 89 ", :empresa => "Instituto Nacional de Migración ", :cargo => "")
    Persona.create(:nombres => "Luz ", :a_paterno => "Cisneros Gonzalez ", :email => "controlope2@bmv.com.mx", :tel_oficina => "53 42 90 00 ext 91 84 ", :tel_movil => " ", :empresa => "Bolsa Mexicana de Valores ", :cargo => "Direccion de Servicios Transaccionales")
    Persona.create(:nombres => "LUZ MARÍA ", :a_paterno => "VÁZQUEZ CORONA ", :email => "", :tel_oficina => "46227923 / 55 29644910 ", :tel_movil => " ", :empresa => " ", :cargo => "")
    Persona.create(:nombres => "MAC J. Gerardo ", :a_paterno => "León Rodríguez ", :email => "jglrodriguez@allnativesystems.com", :tel_oficina => " 55 33 49 42 ", :tel_movil => "044-55-2178-7337 ", :empresa => "ALL NATIVE SYSTEMS, L.L.C ", :cargo => "Especialista en  Sistemas")
    Persona.create(:nombres => "MAGDALENA ", :a_paterno => "MARIACA ", :email => "magdita05@yahoo.com", :tel_oficina => "30 89 20 77 ", :tel_movil => "5529128524 ", :empresa => "PROFESORA DE INGLÉS ", :cargo => "")
    Persona.create(:nombres => "Manuel ", :a_paterno => "Chávez Ferrer ", :email => "manuel@buserdi.com", :tel_oficina => "55 54 68 20 / 55 54 64 29 ", :tel_movil => " ", :empresa => "BUSERDI ", :cargo => "Gerente General")
    Persona.create(:nombres => "MANUEL ", :a_paterno => "HERRADA ", :email => "eherrada@prodigy.net.mx", :tel_oficina => "12 85 36 37/ 38 ", :tel_movil => " ", :empresa => "FIANZAS ", :cargo => "")
    Persona.create(:nombres => "MANUEL ", :a_paterno => "SUGAWARA MURO ", :email => "", :tel_oficina => "55 54 68 43 ", :tel_movil => "04455 29 10 75 48 ", :empresa => " ", :cargo => "")
    Persona.create(:nombres => "Marco Antonio ", :a_paterno => "Cumes ", :email => "marcumes@yahoo.com", :tel_oficina => "00 502 2385 37 25 ", :tel_movil => " ", :empresa => "Marroquín y Asociados ", :cargo => "Abogado OIM")
    Persona.create(:nombres => "Marco Antonio ", :a_paterno => "Ramírez Alvarez ", :email => "marco.ramirez@vvda.com.mx", :tel_oficina => "3626 0731 / 0732 / 0733 ", :tel_movil => "55 2900 8590 ", :empresa => "VVDA Soluciones S.A de C.V ", :cargo => "")
    Persona.create(:nombres => "MARIA ", :a_paterno => "VEGA ", :email => "", :tel_oficina => "01 (722) 22 63 048 ", :tel_movil => " ", :empresa => "INBURSA ", :cargo => "")
    Persona.create(:nombres => "María de Lourdes ", :a_paterno => "Pérez González ", :email => "admon@malo.com.mx", :tel_oficina => "5598 39 63 ", :tel_movil => " ", :empresa => "Martínez López y Asociados ", :cargo => "Administración")
    Persona.create(:nombres => "Maricela ", :a_paterno => "Pinzón ", :email => "", :tel_oficina => "41595729 ", :tel_movil => " ", :empresa => "Chilapa 19 k ", :cargo => "")
    Persona.create(:nombres => "MARICELA ", :a_paterno => "SALAZAR ROMERO ", :email => "", :tel_oficina => "5277 48 99 ", :tel_movil => " ", :empresa => "AVANSOFT ", :cargo => "")
    Persona.create(:nombres => "MARICELA ", :a_paterno => "VELASCO OLMEDO ", :email => "mvelascoo@scotiabank.com.mx", :tel_oficina => "53 46 47 61 ", :tel_movil => " ", :empresa => "SCOTIABANK INVERLAT ", :cargo => "ASESOR FINANCIERO")
    Persona.create(:nombres => "Mariela ", :a_paterno => "Chojulán ", :email => "subdireccion@migracion.gob.gt", :tel_oficina => "00502 2411 2412 ", :tel_movil => " ", :empresa => "Migración GT ", :cargo => "Asistente")
    Persona.create(:nombres => "Mario ", :a_paterno => "Bazail Vandercam ", :email => "mbazail@sistemasdigitales.com.mx", :tel_oficina => "9171 8890 ", :tel_movil => " ", :empresa => "Sistemas Digitales ", :cargo => "Consultor de Proyectos CISCO")
    Persona.create(:nombres => "Mario ", :a_paterno => "Escalante ", :email => "mescalante@allnativesystems.com", :tel_oficina => "55334942 ", :tel_movil => "044-55-4092-0025 ", :empresa => "All Native Systems L.L.C. ", :cargo => "Project Manager")
    Persona.create(:nombres => "MARIO ", :a_paterno => "GARCIADIEGO GONZALEZ ", :email => "", :tel_oficina => "55 54 18 27/7172/5352 ", :tel_movil => " ", :empresa => "NOTARIO (GUATEMALA) ", :cargo => "")
    Persona.create(:nombres => "MARIO  HUGO ", :a_paterno => "MIRANDA ", :email => "", :tel_oficina => "00 (502) 24 11 24 12 ", :tel_movil => " ", :empresa => "GUATEMALA ", :cargo => "SUBDIRECCION")
    Persona.create(:nombres => "MARISELA ", :a_paterno => "OCAMPO ", :email => "mocampo@legosoft.com.mx", :tel_oficina => "91 49 50 40/9149 50 41 ", :tel_movil => " ", :empresa => "LEGOSOFT ", :cargo => "")
    Persona.create(:nombres => "MARTHA ", :a_paterno => "MEZA ", :email => "", :tel_oficina => "56 22 80 30/56 22 85 69 ", :tel_movil => " ", :empresa => "DGSCA ", :cargo => "")
    Persona.create(:nombres => "Mauricio ", :a_paterno => "Arvizu ", :email => "arvizumauricio@gmail.com", :tel_oficina => "53 45 38 98 ", :tel_movil => "55 2068 92 77 ", :empresa => "Cámara de Senadores ", :cargo => "Coordinador")
    Persona.create(:nombres => "Mauricio ", :a_paterno => "Prieto Saldaña ", :email => "academia@guibor.com.mx", :tel_oficina => "5514 2093/5525 0564 ", :tel_movil => "55 1289 4129 ", :empresa => "guibor ", :cargo => "Director de Capacitación")
    Persona.create(:nombres => "Mauricio ", :a_paterno => "Solís ", :email => "mauricio.solis@inali.gob.mx", :tel_oficina => "50042100 x 501 ", :tel_movil => " ", :empresa => "INALI ", :cargo => "Director de Tecnologías de  la Informática")
    Persona.create(:nombres => "Mauricio ", :a_paterno => "Solís  Granados ", :email => "", :tel_oficina => "5004 2100 ext. 501 ", :tel_movil => " ", :empresa => " ", :cargo => "Director del Área de Tecnología")
    Persona.create(:nombres => "Mauricio ", :a_paterno => "Zavala ", :email => "", :tel_oficina => " ", :tel_movil => "55 5618 1693 55 4341 4501 ", :empresa => " ", :cargo => "")
    Persona.create(:nombres => "MEXICANA DE AVIACIÓN ", :a_paterno => " ", :email => "", :tel_oficina => "54 48 88 71 ", :tel_movil => " ", :empresa => "MEXICANA DE AVIACIÓN ", :cargo => "")
    Persona.create(:nombres => "MIGUEL ANGEL ", :a_paterno => "HERNÁNDEZ OROZCO ", :email => "miguel@root.com.mx", :tel_oficina => "56 87 27 70 ", :tel_movil => "04455  16 45 55 45 ", :empresa => "ROOT TECHNOLOGIES ", :cargo => "LÍDER DE PROYECTOS")
    Persona.create(:nombres => "Miguel Ángel ", :a_paterno => "Chanona Carmona ", :email => "mchanona@mx1.ibm.com", :tel_oficina => "5270 6142 ", :tel_movil => "55 2129 2501 ", :empresa => "IBM ", :cargo => "Technical Sales Manager IM and Tivoli")
    Persona.create(:nombres => "Miguel Ángel ", :a_paterno => "Miranda Marroquín ", :email => "mimirand@cisco.com", :tel_oficina => "5267 1805 ", :tel_movil => "55 3223 6305 ", :empresa => "Cisco Systems de México  S.A de C.V ", :cargo => "Utilities Manager")
    Persona.create(:nombres => "Minerva ", :a_paterno => "Aguilar ", :email => "mineaguilar@hotmail.com", :tel_oficina => "56229612 ", :tel_movil => " ", :empresa => "DGSA  UNAM ", :cargo => "Compras")
    Persona.create(:nombres => "MONICA ", :a_paterno => "OSUNA ", :email => "mosuna@compusoluciones.com", :tel_oficina => "50 00 77 77 EXT.3829 ", :tel_movil => " ", :empresa => "COMPUSOLUCIONES ", :cargo => "DESARROLLO DE ASOCIADOS")
    Persona.create(:nombres => "Mónica ", :a_paterno => "González ", :email => "monica.gonzalez@deuno.com", :tel_oficina => "1107 7586 ", :tel_movil => " ", :empresa => "El Banco de Uno ", :cargo => "")
    Persona.create(:nombres => "NANCY ", :a_paterno => "BURTON BARRANCO ", :email => "nburton@procesar.com", :tel_oficina => "25 81 58 88 ", :tel_movil => " ", :empresa => "PROCESAR ", :cargo => "CONTRALORIA NORMATIVA")
    Persona.create(:nombres => "NELLY ", :a_paterno => "VILLEGAS ", :email => "nelly.villegas@opensys-mexico.com", :tel_oficina => "91 16 29 60 EXT. 1119 ", :tel_movil => " ", :empresa => "OPENSYSTEM ", :cargo => "")
    Persona.create(:nombres => "NORMA ELENA ", :a_paterno => "ORTIZ AQUIHUA ", :email => "", :tel_oficina => "56 24 20 22 EXT 70115 ", :tel_movil => " ", :empresa => "BOLSA DE TRABAJO UPICSA ", :cargo => "")
    Persona.create(:nombres => "Octavio ", :a_paterno => " ", :email => "octavio.luis@gcis.com.mx", :tel_oficina => "1990 3640 ", :tel_movil => " ", :empresa => "GCIS ", :cargo => "")
    Persona.create(:nombres => "OFELIA ", :a_paterno => "JIMENEZ ", :email => "", :tel_oficina => "56 22 46 77 ", :tel_movil => " ", :empresa => "INSTITUTO DE CIENCIAS NUCLEARES ", :cargo => "")
    Persona.create(:nombres => "Omar ", :a_paterno => "Romero Hernández ", :email => "oromero@reduno.com.mx", :tel_oficina => "5490 7206 ", :tel_movil => "55 5412 3409 ", :empresa => "Red uno ", :cargo => "Gerente de Infraestructura Especial")
    Persona.create(:nombres => "Oscar ", :a_paterno => "Chávez López ", :email => "", :tel_oficina => "1163 0356 ", :tel_movil => " ", :empresa => "Hoda ", :cargo => "Asesor de Servicio")
    Persona.create(:nombres => "Oscar ", :a_paterno => "Nuñez ", :email => "", :tel_oficina => "56 22 70 11 ", :tel_movil => " ", :empresa => "DIFUSIÓN CULTURAL ", :cargo => "")
    Persona.create(:nombres => "Óscar ", :a_paterno => "Guzmán ", :email => "oscar.guzman@axtel.com.mx", :tel_oficina => "50921411 ", :tel_movil => "36140498 ", :empresa => "Axtel ", :cargo => "Gerente Soporte Técnico CPE y SI")
    Persona.create(:nombres => "Pablo ", :a_paterno => "Padilla ", :email => "pablop@arscite.com", :tel_oficina => " ", :tel_movil => "55 3643 28 22 ", :empresa => "ARS Cite ", :cargo => "")
    Persona.create(:nombres => "PATRICIA ", :a_paterno => "FLORES ", :email => "infanson@ixe.com.mx", :tel_oficina => "56 66 32 26 ", :tel_movil => " ", :empresa => "IXE ", :cargo => "")
    Persona.create(:nombres => "Patricia ", :a_paterno => "Olmos Malagon ", :email => "paol@sisorg.com.mx", :tel_oficina => "5256 45 17 ", :tel_movil => " ", :empresa => "SIS KLE ", :cargo => "")
    Persona.create(:nombres => "Paulina ", :a_paterno => "Álvarez ", :email => "", :tel_oficina => "91262222 ext. 2424 ", :tel_movil => " ", :empresa => "BB Mundo ", :cargo => "")
    Persona.create(:nombres => "Ramón ", :a_paterno => "Mondragón Sotelo ", :email => "ramon@aquainteractive.com.mx", :tel_oficina => "8596 5748 y 8596 5749 ", :tel_movil => " ", :empresa => "Aquainteractive ", :cargo => "Director General")
    Persona.create(:nombres => "RAÚL ", :a_paterno => "SANCHEZ ", :email => "", :tel_oficina => "5622 48 10 ", :tel_movil => " ", :empresa => "FACULTAD DE CIENCIAS ", :cargo => "")
    Persona.create(:nombres => "RAYMUNDO ", :a_paterno => "MERIDA ", :email => "", :tel_oficina => " ", :tel_movil => "044 55 2847 2874 ", :empresa => "MANTENIMIENTO ", :cargo => "")
    Persona.create(:nombres => "Reynaldo ", :a_paterno => "Ayala Espinoza de los Monteros ", :email => "", :tel_oficina => "53 87 24 00 x 18304 ", :tel_movil => " ", :empresa => "INM ", :cargo => "Subdirector de Recursos Materiales")
    Persona.create(:nombres => "RICARDO ", :a_paterno => "CASTILLO ", :email => "", :tel_oficina => "56 22 70 26/56 65 22 09 ", :tel_movil => " ", :empresa => " ", :cargo => "")
    Persona.create(:nombres => "Ricardo ", :a_paterno => "Legorreta ", :email => "ricardo_legorreta@legosoft.com.mx", :tel_oficina => "9149 5040 ", :tel_movil => " ", :empresa => "LegoSoft ", :cargo => "Director General")
    Persona.create(:nombres => "Ricardo ", :a_paterno => "Ramírez Montoya ", :email => "rrm@gae.structura.com.mx", :tel_oficina => "52730393 / 52730587 ", :tel_movil => " ", :empresa => "GAE Structura ", :cargo => "")
    Persona.create(:nombres => "Ricardo ", :a_paterno => "Ramírez Montoya ", :email => "rrm@gae.structura.com.mx", :tel_oficina => "52 73 03 93 / 52 73 05 87 ", :tel_movil => " ", :empresa => "GAE Structura ", :cargo => "")
    Persona.create(:nombres => "RITA ELISA ", :a_paterno => "FLORES SANCHEZ ", :email => "rita.flores@terra.com.gt", :tel_oficina => "00 (502) 23 66 81 72 ", :tel_movil => "55871640 ", :empresa => "CONTABILIDAD GUATEMALA ", :cargo => "CONTADORA")
    Persona.create(:nombres => "ROBERTO ", :a_paterno => "MURILLO ", :email => "roberto.murillo@itzmanova.com", :tel_oficina => "91 71 75 08 ", :tel_movil => "044 55 39 55 81 69 ", :empresa => "ITZMANOVA ", :cargo => "")
    Persona.create(:nombres => "ROCIO ", :a_paterno => "VILLAZON ", :email => "", :tel_oficina => "52 30 02 00/17 EXT. 0218 ", :tel_movil => " ", :empresa => "MONEX ", :cargo => "")
    Persona.create(:nombres => "Rodrigo Fernando ", :a_paterno => "Alonso Pinzón ", :email => "rodrigo@root.com.mx", :tel_oficina => "56 87 27 70 ", :tel_movil => "04455 54 19 91 00 ", :empresa => "Root Technologies S.C. ", :cargo => "Director General")
    Persona.create(:nombres => "Rogelio ", :a_paterno => "García ", :email => "roger_regs@yahoo.com", :tel_oficina => "52711967  52725768 ", :tel_movil => "04455 27 07 11 42 ", :empresa => "Advirsity ", :cargo => "Director / Maestro")
    Persona.create(:nombres => "Rosa Maria ", :a_paterno => "Cardenas González ", :email => "rcontreras@grupo-dice.com", :tel_oficina => "800006415 ", :tel_movil => "5534557898 ", :empresa => "Grupo Dice ", :cargo => "Ejecutivo de cuenta")
    Persona.create(:nombres => "Rosa María ", :a_paterno => "Castro Ruiz ", :email => "", :tel_oficina => "5622 4810 y 5622 4900 ", :tel_movil => " ", :empresa => "UNAM ", :cargo => "Jefa de Bienes y Suministros")
    Persona.create(:nombres => "RUBEN ", :a_paterno => "GODINEZ ORTEGA ", :email => "ruben@root.com.mx", :tel_oficina => "56 87 27 70 ", :tel_movil => "04455 91850913 ", :empresa => "ROOT TECHNOLOGIES ", :cargo => "ANALISTA")
    Persona.create(:nombres => "Salvador ", :a_paterno => "Domínguez León ", :email => "salvador@bbmundo.com", :tel_oficina => "9126220 x 2253 ", :tel_movil => " ", :empresa => "BBMundo Direct S.A. de C.V. ", :cargo => "Director de Operaciones")
    Persona.create(:nombres => "SAMUEL ", :a_paterno => "LASCANI ", :email => "", :tel_oficina => "58 30 35 65 ", :tel_movil => " ", :empresa => "PIZARRONES ", :cargo => "ENCARGADO")
    Persona.create(:nombres => "Sandra ", :a_paterno => "Arestegui López ", :email => "sandra.arestegui@infotec.com.mx", :tel_oficina => "5624 28 00 x 4707 ", :tel_movil => "2341 33 80 ", :empresa => "Infotec ", :cargo => "")
    Persona.create(:nombres => "Scootiabank ", :a_paterno => " ", :email => "", :tel_oficina => "53464715 ", :tel_movil => " ", :empresa => " ", :cargo => "")
    Persona.create(:nombres => "Sebastián ", :a_paterno => "Hiernaux ", :email => "sebastian.x.hiernaux@jpmchase.com", :tel_oficina => "55 40 94  17 ", :tel_movil => " ", :empresa => "JP Morgan ", :cargo => "Associate")
    Persona.create(:nombres => "Sebastián ", :a_paterno => "Mantilla ", :email => "sebastian.mantilla@gmail.com", :tel_oficina => "04455 16 49 43 13 ", :tel_movil => " ", :empresa => " ", :cargo => "")
    Persona.create(:nombres => "Segundo ", :a_paterno => "Pérez ", :email => "segundo.perez@prodigy.net.mx", :tel_oficina => "10 87 84 00 ", :tel_movil => "04455 54 32 98 24 ", :empresa => " ", :cargo => "DISEÑADOR")
    Persona.create(:nombres => "Selenne ", :a_paterno => "Herrera ", :email => "", :tel_oficina => " ", :tel_movil => "04455 34 43 41 38 ", :empresa => " ", :cargo => "Limpieza")
    Persona.create(:nombres => "TACA ", :a_paterno => "VUELOS ", :email => "", :tel_oficina => "01 800 400 8222 ", :tel_movil => " ", :empresa => " ", :cargo => "")
    Persona.create(:nombres => "Telmex ", :a_paterno => " ", :email => "", :tel_oficina => "56051207 ", :tel_movil => " ", :empresa => "Teléfonos ", :cargo => "Técnicos")
    Persona.create(:nombres => "Tere ", :a_paterno => "Herrera ", :email => "", :tel_oficina => "53453000 EXT. 5240 y 5237 ", :tel_movil => " ", :empresa => "Comisión Bicentenario ", :cargo => "Contadora")
    Persona.create(:nombres => "Tomás ", :a_paterno => "Orozco La Roche ", :email => "tomas.orozco@eds.com", :tel_oficina => "52611301 ", :tel_movil => " ", :empresa => "EDS México SA de CV ", :cargo => "Govemment Director")
    Persona.create(:nombres => "Torre Café ", :a_paterno => " ", :email => "", :tel_oficina => "9151 17 14 ", :tel_movil => " ", :empresa => " ", :cargo => "")
    Persona.create(:nombres => "VALERIA ", :a_paterno => " ", :email => "", :tel_oficina => "52 08 71 81 ", :tel_movil => " ", :empresa => "NUL-UNU ", :cargo => "")
    Persona.create(:nombres => "Verónica ", :a_paterno => "Almaraz ", :email => "", :tel_oficina => "5687 7202 / 5687 7497 ", :tel_movil => " ", :empresa => "IXE Banco ", :cargo => "Ejecutiva")
    Persona.create(:nombres => "Verónica ", :a_paterno => "Fernández ", :email => "vero_1197@hotmail.com", :tel_oficina => "56008609 ", :tel_movil => " ", :empresa => "ASIESC ", :cargo => "Asistente contadora")
    Persona.create(:nombres => "Verónica ", :a_paterno => "Herrada ", :email => "monicax@prodigy.net.mx", :tel_oficina => "12 85 36 39 ", :tel_movil => " ", :empresa => "FIANZAS ", :cargo => "")
    Persona.create(:nombres => "Vicente ", :a_paterno => "Aguinaco Bravo ", :email => "vaguinaco@cfe.gob.mx", :tel_oficina => "52294400 ext. 44000,44001 ", :tel_movil => " ", :empresa => "CFE ", :cargo => "Gerente de Protección Ambiental")
    Persona.create(:nombres => "Vladimir ", :a_paterno => "Fajardo Ricard ", :email => "vladimir@root.com.mx", :tel_oficina => "56 87 27 70 ", :tel_movil => "04455 13 65 77 79 ", :empresa => "ROOT TECHNOLOGIES ", :cargo => "PROGRAMADOR")
    Persona.create(:nombres => "Wendy ", :a_paterno => "Carrillo ", :email => "wensastiga@hotmail.com", :tel_oficina => " ", :tel_movil => "5536567875 ", :empresa => "Becarios Benito Juárez ", :cargo => "")
    Persona.create(:nombres => "WISSEN, S.C. ", :a_paterno => " ", :email => "", :tel_oficina => "442 234 70 76 ", :tel_movil => " ", :empresa => "WISSEN, S.C. ", :cargo => "")
    Persona.create(:nombres => "Ximena ", :a_paterno => "Díaz Rodríguez ", :email => "xdiaz@bansefi.gob.mx", :tel_oficina => "5481 3300 ext 4038 ", :tel_movil => " ", :empresa => "Bansefi ", :cargo => "Analista Senior")
    Persona.create(:nombres => "YAMIL ", :a_paterno => "JIMENEZ ATALA ", :email => "yjimenez@foundrynet.com", :tel_oficina => "50 91 43 52/56 68 35 00 ", :tel_movil => " ", :empresa => "FOUNDRY ", :cargo => "")
    Persona.create(:nombres => "YLEANA ", :a_paterno => "HERRERA TRUJANO ", :email => "asiesc@hotmail.com", :tel_oficina => "56 00 86 09/56 94 25 25 ", :tel_movil => " ", :empresa => "ASIE ", :cargo => "Contadora")
    Persona.create(:nombres => "YOLANDA ", :a_paterno => "OAXACA ", :email => "yolanda.oaxaca@wissenmx.com", :tel_oficina => "91 71 75 05 ", :tel_movil => " ", :empresa => "WISSEN, S.C. ", :cargo => "")
    Persona.create(:nombres => "Zyanya ", :a_paterno => "Miranda Molina ", :email => "zyanya@amesol.org.mx", :tel_oficina => "5004-9472, 73 ", :tel_movil => " ", :empresa => "AMESOL ", :cargo => "Coordinadora General")


  end

  def self.down
    drop_table :personas
  end
end
